# Generated by Django 4.2 on 2023-05-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pro",
            name="create",
        ),
    ]
